### ISSUE TITLE
Feature request for 8 state predictions

### ISSUE THREAD

**Issue by ragunyrasta** [psipred/s4pred#1]
I love how fast and practical this program is. Thanks! Is there any chance we can see it's predictions extended to 8-states as opposed to just 3 states?

**Comment by limitloss** [comment]
Thanks! Currently there aren't any concrete plans to extend the model to 8-state predictions but it's definitely a possibility. Is there anything particular you have in mind for the 8-states, e.g. benchmarking against another model? 

There's a few ways to go about it but going with the most obvious, the main step in adding 8-state prediction would be regenerating the pseudo-labelled set with a separate 8-state homology based predictor (that's been trained on a CATH-based split against CB513) as PSIPRED is a 3-state predictor. That probably risks a bit of an overhaul but its possible... a different way of doing it could be just adding the 8-state predictions in S4PRED's fine-tuning step, but that may not be the best for comparative benchmarking...

**Comment by DanBuchan** [comment]
Is there even enough reliable data for S8 predictions and are the other SS classes biologically relevant? That's always been a historical barrier to bothering and why bioinformaticians have generally not focussed on anything other the S3 prediction. Turns and Bends don't have fixed regular geometry so it is unclear to me what the utility of such a prediction would be. Though 310-helix may be a worthwhile class to identify. And pi-helices do have functional impacts. S6 prediction might be a more fruitful/useful avenue.

**Comment by ragunyrasta** [comment]
Thanks for the discussion. The main motivations for S>3 prediction from 
my end are a ton of new protein sequences emerging and the potential of 
generated sequences from generative AI.

s4pred runs very fast - just enough to seriously consider doing virtual 
experiments on a billion sequences. S3 is good, but the info just isn't 
there to differentiate a set of sequences in between 2 helices which 
causes the 2 helices to do a complete U-turn and be parallel to each 
other as opposed to the 2 helices being at right angles to each other.

S>3 would lead to better training and predictions on some of these 
sequences.  Perhaps we need to first figure out what the important 
states are, to achieve this objective.

regards
-Ragu
