### ISSUE TITLE
Parellisization using JobLib

### ISSUE THREAD

**Issue by devhimd19** [psipred/s4pred#3]
Can S4 Pred be parallelsized using JobLib so that it can run in all the cores of CPU

**Comment by DanBuchan** [comment]
The developer of S4Pred no longer works in our group so this is unlikely to be added to the code. If you would like to add such functionality then we will happily review pull requests

However, larger scale S4Pred analyses are usually ermbarrassingly parallel running over mulitple input sequences. It is fairly trivial to write a helper python script that uses multiprocess pool to run jobs in parallel over many cores/hyperthreads on one machine. Again, this is something you would need to write for yourself. I note also that you could use something like Common Workflow Language to accomplish this too.
