### ISSUE TITLE
Results are showing different while running ml model and command line 

### ISSUE THREAD

**Issue by devhimd19** [psipred/s4pred#4]
When i am running the code in ml model the secondary strucutre sequence result is different and when i am running using the python script given in your github using the single command line the results are different. Why this variation is observed and why it is not constant while running the ml models and using single command line.

**Comment by DanBuchan** [comment]
Can you give more details? What comandline strings are you using to run this? What is 'ml model' in this context?

**Comment by DanBuchan** [comment]
Closing this as we got no response or clarifying details
